version: '3'
services:
  app:
    build:
      context: .
      dockerfile: containers/react/Dockerfile
    volumes:
      - .:/opt/webapp
      - node_modules:/opt/webapp/node_modules
    ports:
      - 3000:3000
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/opt/webapp/public
      - tmp-data:/opt/webapp/tmp
    ports:
      - 8080:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  node_modules:
